
import-land:
  build: "src/import-land"
  command: ./import-land.sh
  links:
  - postgis:db

smrender:
  build: src/smrender
  volumes:
   - ./import:/import
imposm2:
  build: src/imposm2
  command: ./import-pbf.sh
  volumes:
   - ./import:/data/import
  volumes_from:
   - cache
  links:
   - postgis:db

imposm3:
  build: "src/import-osm"
  command: ./import-pbf.sh
  volumes:
   - ./import:/data/import
  volumes_from:
   - cache
  links:
   - postgis:db
